export const AuditEvents = {
  // User Management
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_REACTIVATED: "USER_REACTIVATED",
  USER_DISABLED: "USER_DISABLED",
  USER_ARCHIVED: "USER_ARCHIVED",
  USER_DELETED: "USER_DELETED",
  USER_ROLE_ASSIGNED: "USER_ROLE_ASSIGNED",
  USER_ROLE_REMOVED: "USER_ROLE_REMOVED",
  USER_SESSION_REVOKED: "USER_SESSION_REVOKED",
  USER_PASSWORD_RESET_ADMIN: "USER_PASSWORD_RESET_ADMIN",

  // Role Management
  ROLE_CREATED: "ROLE_CREATED",
  ROLE_UPDATED: "ROLE_UPDATED",
  ROLE_DELETED: "ROLE_DELETED",
  ROLE_PERMISSION_ASSIGNED: "ROLE_PERMISSION_ASSIGNED",
  ROLE_PERMISSION_REMOVED: "ROLE_PERMISSION_REMOVED",

  // Permission Management
  PERMISSION_CREATED: "PERMISSION_CREATED",
  PERMISSION_DELETED: "PERMISSION_DELETED",

  // Authentication
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_TOKEN_REFRESHED: "AUTH_TOKEN_REFRESHED",

  // Two-Factor Authentication
  TWO_FACTOR_ENABLED: "TWO_FACTOR_ENABLED",
  TWO_FACTOR_DISABLED: "TWO_FACTOR_DISABLED",
  TWO_FACTOR_FAILED: "TWO_FACTOR_FAILED",
  TWO_FACTOR_SUCCESS: "TWO_FACTOR_SUCCESS",
  TWO_FACTOR_BACKUP_CODE_USED: "TWO_FACTOR_BACKUP_CODE_USED",

  // Password
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",

  // Authorization
  PERMISSION_GRANTED: "PERMISSION_GRANTED",
  PERMISSION_DENIED: "PERMISSION_DENIED",

  // System Settings
  SYSTEM_SETTING_UPDATED: "SYSTEM_SETTING_UPDATED",
  SYSTEM_SETTINGS_BULK_UPDATED: "SYSTEM_SETTINGS_BULK_UPDATED",
  MAINTENANCE_MODE_ENABLED: "MAINTENANCE_MODE_ENABLED",
  MAINTENANCE_MODE_DISABLED: "MAINTENANCE_MODE_DISABLED",

  // Security
  RATE_LIMIT_TRIGGERED: "RATE_LIMIT_TRIGGERED",
  SESSION_REVOKED: "SESSION_REVOKED",
} as const;

export type AuditEventType = (typeof AuditEvents)[keyof typeof AuditEvents];

export const AuditModules = {
  AUTH: "auth",
  USERS: "users",
  ROLES: "roles",
  PERMISSIONS: "permissions",
  RBAC: "rbac",
  AUDIT: "audit",
  SYSTEM: "system",
  DASHBOARD: "dashboard",
} as const;

export type AuditModuleType = (typeof AuditModules)[keyof typeof AuditModules];
