export const SecurityEvents = {
  // Authentication
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGIN_PENDING_2FA: "AUTH_LOGIN_PENDING_2FA",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_TOKEN_REFRESHED: "AUTH_TOKEN_REFRESHED",

  // Two-Factor Authentication
  TWO_FACTOR_ENABLED: "TWO_FACTOR_ENABLED",
  TWO_FACTOR_DISABLED: "TWO_FACTOR_DISABLED",
  TWO_FACTOR_FAILED: "TWO_FACTOR_FAILED",
  TWO_FACTOR_SUCCESS: "TWO_FACTOR_SUCCESS",
  TWO_FACTOR_BACKUP_CODE_USED: "TWO_FACTOR_BACKUP_CODE_USED",

  // Password
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_FAILED: "PASSWORD_RESET_FAILED",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",

  // RBAC - Permissions
  PERMISSION_GRANTED: "PERMISSION_GRANTED",
  PERMISSION_DENIED: "PERMISSION_DENIED",

  // RBAC - Roles
  ROLE_CREATED: "ROLE_CREATED",
  ROLE_DELETED: "ROLE_DELETED",
  ROLE_UPDATED: "ROLE_UPDATED",
  ROLE_ASSIGNED: "ROLE_ASSIGNED",
  ROLE_REMOVED: "ROLE_REMOVED",

  // RBAC - Permissions Management
  PERMISSION_CREATED: "PERMISSION_CREATED",
  PERMISSION_DELETED: "PERMISSION_DELETED",
  PERMISSION_ASSIGNED_TO_ROLE: "PERMISSION_ASSIGNED_TO_ROLE",
  PERMISSION_REMOVED_FROM_ROLE: "PERMISSION_REMOVED_FROM_ROLE",

  // Rate Limiting
  RATE_LIMIT_TRIGGERED: "RATE_LIMIT_TRIGGERED",
} as const;

export type SecurityEventType =
  (typeof SecurityEvents)[keyof typeof SecurityEvents];
